version: '3.8'
services:
  web:
    image: "ghcr.io/bfssi-bioinformatics-lab/pptm:simplify_upload"
    command: "gunicorn config.wsgi:application --bind 0.0.0.0:8080"
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DJANGO_SETTINGS_MODULE=config.settings.local
