# Generated by Django 5.0.9 on 2024-10-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pptp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="has_multiple_barcodes",
            field=models.BooleanField(
                default=False, help_text="Check if product has multiple barcodes"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="has_multiple_nutrition_facts",
            field=models.BooleanField(
                default=False,
                help_text="Check if product has multiple nutrition facts tables",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_variety_pack",
            field=models.BooleanField(
                default=False, help_text="Check if this is a variety/multi-pack product"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="product_name",
            field=models.CharField(
                default="Product name",
                help_text="Full product name as shown on packaging",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
