# Generated by Django 5.0.9 on 2024-11-01 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pptp", "0006_alter_barcode_product_alter_ingredients_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barcode",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="barcodes",
                to="pptp.product",
            ),
        ),
        migrations.AlterField(
            model_name="ingredients",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredients",
                to="pptp.product",
            ),
        ),
        migrations.AlterField(
            model_name="nutritionfacts",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nutrition_facts",
                to="pptp.product",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_images",
                to="pptp.product",
            ),
        ),
    ]
