# Generated by Django 4.2.3 on 2025-03-19 18:43

from django.db import migrations, models
import pptp.models.products
import pptp.storage.azure


class Migration(migrations.Migration):
    dependencies = [
        ("pptp", "0009_alter_product_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="has_preparation_instructions",
            field=models.BooleanField(
                default=False,
                help_text="Check if this has preparation instructions on the package",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_individually_packaged",
            field=models.BooleanField(
                default=False,
                help_text="Check if this is multiple individually wrapped items, e.g. granola bars",
            ),
        ),
        migrations.AlterField(
            model_name="barcode",
            name="image",
            field=pptp.models.products.AzureImageField(
                blank=True,
                help_text="Image file",
                null=True,
                storage=pptp.storage.azure.AzureBlobStorage(),
                upload_to=pptp.models.products.get_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="ingredients",
            name="image",
            field=pptp.models.products.AzureImageField(
                blank=True,
                help_text="Image file",
                null=True,
                storage=pptp.storage.azure.AzureBlobStorage(),
                upload_to=pptp.models.products.get_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="nutritionfacts",
            name="image",
            field=pptp.models.products.AzureImageField(
                blank=True,
                help_text="Image file",
                null=True,
                storage=pptp.storage.azure.AzureBlobStorage(),
                upload_to=pptp.models.products.get_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=pptp.models.products.AzureImageField(
                blank=True,
                help_text="Image file",
                null=True,
                storage=pptp.storage.azure.AzureBlobStorage(),
                upload_to=pptp.models.products.get_upload_path,
            ),
        ),
    ]
