# Generated by Django 4.2.3 on 2025-05-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pptp", "0010_product_has_preparation_instructions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="is_individually_packaged",
            field=models.BooleanField(
                default=False,
                help_text="Check if this is multiple individually wrapped items. The important thing is if there is a physical wrapper around each individual object. It affects how the reference amount is applied",
            ),
        ),
    ]
