# Generated by Django 4.2.3 on 2025-05-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pptp", "0011_alter_product_is_individually_packaged"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="needs_manual_verification",
            field=models.BooleanField(
                default=False,
                help_text="Product is difficult to photograph clearly or otherwise classify, flag for manual verification",
            ),
        ),
    ]
