# Generated by Django 4.2.3 on 2025-05-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pptp", "0012_product_needs_manual_verification"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="package_size",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Number for the total package size",
                max_digits=7,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="package_size_unit",
            field=models.CharField(
                choices=[
                    ("MG", "Milligrams"),
                    ("G", "Grams"),
                    ("KG", "Kilograms"),
                    ("ML", "Millilitres"),
                    ("L", "Litres"),
                    ("OTH", "Other"),
                ],
                default="OTH",
                help_text="Unit for the total package size",
                max_length=3,
            ),
        ),
    ]
