# Generated by Django 4.2.3 on 2025-08-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pptp", "0013_product_package_size_product_package_size_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="has_disease_risk_reduction_claim",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="has_function_claim",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="has_general_health_claim",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="has_implied_nonspecific_claim",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="has_logos_icons",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="has_nutrient_content_claim",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="has_nutrient_function_claim",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="has_probiotic_claim",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="has_quantitative_nutrient_declaration",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="has_supplemental_caution_id",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="has_therapeutic_claim",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="has_third_party_label",
            field=models.BooleanField(default=False),
        ),
    ]
