# Generated by Django 4.2.3 on 2025-10-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pptp", "0014_product_has_disease_risk_reduction_claim_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_tds",
            field=models.BooleanField(
                default=False,
                help_text="Check if this product is part of the Total Diet Study",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_supplemented_food",
            field=models.BooleanField(
                default=False,
                help_text="Check if this is a Supplemented Food as defined by the regulations (whether or not it has a supplemental caution label)",
            ),
        ),
    ]
