# Generated by Django 4.2.3 on 2025-10-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pptp", "0015_product_is_tds_alter_product_is_supplemented_food"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
