# Generated by Django 4.2.3 on 2025-10-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pptp", "0016_product_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="manual_barcode",
            field=models.CharField(
                blank=True,
                default="",
                help_text="barcode number entered by user",
                max_length=50,
            ),
        ),
    ]
