# Generated by Django 4.2.3 on 2025-12-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pptp", "0017_product_manual_barcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="storage_condition",
            field=models.CharField(
                choices=[
                    ("shelf_stable", "Shelf stable"),
                    ("fridge", "Fridge"),
                    ("freezer", "Freezer"),
                ],
                default="shelf_stable",
                help_text="Required storage condition",
                max_length=12,
            ),
        ),
    ]
