# Generated by Django 4.2.3 on 2025-12-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pptp", "0019_product_primary_package_material_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="secondary_package_material",
            field=models.CharField(
                blank=True,
                choices=[
                    ("glass", "Glass"),
                    ("metal", "Metal"),
                    ("paper", "Paper/paperboard"),
                    ("plastic_pet", "Plastic - PET - 1"),
                    ("plastic_hdpe", "Plastic - HDPE - 2"),
                    ("plastic_pvc", "Plastic - PVC - 3"),
                    ("plastic_ldpe", "Plastic - LDPE - 4"),
                    ("plastic_pp", "Plastic - PP - 5"),
                    ("plastic_ps", "Plastic - PS - 6"),
                    ("plastic_other", "Plastic - OTHER - 7"),
                    ("plastic_unknown", "Plastic - Unknown"),
                    ("other", "Other"),
                ],
                help_text="Secondary packaging (optional)",
                max_length=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="storage_condition",
            field=models.CharField(
                choices=[
                    ("shelf_stable", "Shelf Stable"),
                    ("fridge", "Fridge"),
                    ("freezer", "Freezer"),
                ],
                default="shelf_stable",
                help_text="Required storage condition",
                max_length=12,
            ),
        ),
    ]
