# Generated by Django 4.2.3 on 2026-01-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pptp", "0020_alter_product_secondary_package_material_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="num_units",
            field=models.IntegerField(
                blank=True, help_text="Number of individual units (optional)", null=True
            ),
        ),
    ]
