# Generated by Django 4.2.3 on 2026-01-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pptp", "0021_product_num_units"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="has_multiple_ingredients",
            field=models.BooleanField(
                default=False, help_text="Check if product has multiple LOI photos"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="has_multiple_other_images",
            field=models.BooleanField(
                default=False, help_text="Check if product has multiple other photos"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="has_multiple_side_images",
            field=models.BooleanField(
                default=False,
                help_text="Check if product has multiple side of package photos",
            ),
        ),
    ]
