# Generated by Django 4.2.3 on 2026-01-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pptp", "0023_product_source_batch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="source_batch",
            field=models.CharField(
                choices=[
                    ("2025_snapcan", "SNAP-CAN 2025"),
                    ("2025_baked_desserts", "2025 Baked Desserts Collection"),
                    ("tds", "Total Diet Study"),
                    ("2025_supp_food", "2025 Supplemented Food Collection"),
                    ("2025_frozen_entrees", "2025 Frozen Entrees Collection"),
                ],
                help_text="Product collection batch",
                null=True,
            ),
        ),
    ]
